{{- if .Values.global.objectStore.minio.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.minio.fullname" . }}
  labels:
    component: minio
{{ include "presto.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: minio
{{ include "presto.labels" . | indent 6 }}
  replicas: {{ .Values.minio.deploy.replicas }}
  strategy:
{{ toYaml .Values.minio.deploy.updateStrategy | trim | indent 4 }}
  template:
    metadata:
      labels:
        component: minio
{{ include "presto.labels" . | indent 8 }}
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.deploy.container.image }}:{{ .Values.minio.deploy.container.tag }}
          imagePullPolicy: {{ .Values.minio.deploy.container.pullPolicy }}
          command:
          - minio
          args:
          {{ if .Values.minio.azure.enable }}
          - gateway
          - azure
          {{ else }}
          - server
          - /data
          {{ end }}
          env:
          - name: MINIO_ACCESS_KEY
            value: {{ .Values.global.objectStore.accessKey }}
          - name: MINIO_SECRET_KEY
            value: {{ .Values.global.objectStore.accessSecret }}
          ports:
          - containerPort: {{ .Values.minio.service.port }}
            name: minio
          {{ if not .Values.minio.azure.enable }}
          volumeMounts:
          - mountPath: /data
            name: cloud-storage
      volumes:
        - name: cloud-storage
          persistentVolumeClaim:
            claimName: {{ template "presto.minio.fullname" . }}-storage
          {{ end }}
{{- end }}
