apiVersion: v1
kind: Service
metadata:
  name: {{ include "hindsight.fullname" . }}-profile
  labels:
    app: hindsight-profile
    {{- include "hindsight.labels" . | nindent 4 }}
spec:
  type: {{ .Values.profile.service.type }}
  ports:
    - port: 9568
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: hindsight-profile
    {{- include "hindsight.selectorLabels" . | nindent 4 }}
