apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hindsight.fullname" . }}-broadcast-key-base
type: Opaque
stringData:
  secret_key_base: {{ .Values.broadcast.secret_key_base | default "Tb9H+b8QK6Q9MNlMx0+FGM5SkmjJOFGlkI7UH1UZNA0xnUpUtxVraeVAn1RFppUg" | quote }}
