{{- if .Values.strimzi.enabled -}}
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: dead-letter-queue
  labels:
    strimzi.io/cluster: streaming-service
spec:
  partitions: 1
  replicas: 1
  config: {}
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: event-stream
  labels:
    strimzi.io/cluster: streaming-service
spec:
  partitions: 1
  replicas: 1
  config: {}
{{- end -}}
