name: presto
apiVersion: v1
description: Hadoop-less data storage
version: 1.3.0
keywords:
- presto
- hive-metastore
- cloud-object-store
- minio
sources:
- https://github.com/prestodb/presto
- https://github.com/apache/hive
- https://github.com/minio/minio
- https://github.com/helm/helm
