{{- if .Values.postgres.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.postgres.fullname" . }}-init
  labels:
    component: postgres
{{ include "presto.labels" . | indent 4 }}
data:
  init.sql: |-
    CREATE DATABASE {{ .Values.postgres.db.name }};
    CREATE USER {{ .Values.postgres.db.user | required "presto.postgres.db.user must be set" }} WITH PASSWORD '{{ .Values.postgres.db.password | required "presto.postgres.db.password must be set" }}';
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgres.db.name }} TO {{ .Values.postgres.db.user | required "presto.postgres.db.user must be set" }};
{{- end }}
