apiVersion: v1
kind: Service
metadata:
  name: {{ template "presto.fullname" . }}
  labels:
    component: presto
    role: coordinator
{{ include "presto.labels" . | indent 4 }}
  annotations:
    prometheus.io/port:  "9483"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.presto.service.type }}
  ports:
  - port: {{ .Values.presto.service.port }}
    targetPort: http-coord
    name: http-coord
  - port: 9483
    targetPort: metric-port
    name: metric-port
  selector:
    component: presto
    role: coordinator
{{ include "presto.labels" . | indent 4 }}
